### ISSUE TITLE
Introduce features required to implement interop testing in Testground

### ISSUE THREAD

**Issue by laurentsenta** [testground/testground#1340]
## Description

We're working on interoperability tests with the go & rust libp2p projects,
we want to express:

- test cross-version compatibility in go: a go test built with different go versions and different libraries versions,
- test cross-version compatibility in rust: a rust test built with different rust versions and different libraries versions,
- test cross-implementation compatibility: a combination of the tests above that compares go and rust implementations.

There are ways to "hack" these using file manipulations, artifacts rewrites, etc. But we want to move past scripts & tweaks now.

## What defines this endeavour to be complete?

- [x] go interoperability testing
  - [x] have the ability to run the same test written in go, but using different modfiles and different go versions, (#1337)
- [ ] ~rust interoperability testing~ (will be implemented later)
  - [ ] implement native rust support,
  - [ ] add dependencies rewrite in rust (similar to go), and maybe selectors support too (to be discussed with Rust maintainers),
  - [ ] have the ability to run the same test written in rust, but using different cargofiles,
- [x] go - rust interoperability testing (https://github.com/testground/testground/issues/1357)
  - [x] add the ability to run multiple test plan (one test in go and one test in rust) with the same composition file, (#1305)

**Comment by laurentsenta** [comment]
Note from call with @mxinden

we don't need to introduce native rust support yet: we'll use the generic docker builder and pass rust build flags via the build options (implemented in #1337)

**Comment by laurentsenta** [comment]
Closing this ticket as we have all the features we planned and need,
see https://github.com/libp2p/test-plans/pull/26 we're missing a few features to help with maintenance and stability, we'll work on these separately.
