### ISSUE TITLE
EPIC: Speed up development with improved integration testing tooling (no more shell scripts or flakiness)

### ISSUE THREAD

**Issue by laurentsenta** [testground/testground#1368]
eta: 2023-01

It looks like we have 2 ways to run integration tests:

1. https://github.com/testground/testground/tree/master/pkg/cmd/itest
2. https://github.com/testground/testground/tree/master/integration_tests

Some of these are testing the same commands.
The `itest` package makes `go test -v ./pkg/...` is annoying to use because integration tests are creating a lot of noise amongts unit tests.

We should merge all these tests to a single, clearer location.

A few notes:

- Using go instead of shell make sense here, the [header.sh](https://github.com/testground/testground/blob/master/integration_tests/header.sh) script is already quite complex.
- We need to take into account the fact that some integration tests require setup (k8s)
- Bonus point for parallelizing tests, we might be able to use a github action's matrix.

## Design

- [x] Review approaches
     - [x] https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md

## Tasks

- [x] Create a integration_tests package that relies on [golang's testing tools]
    - [x] Implement the tooling required to make these tests maintainable(https://github.com/testground/testground/tree/master/pkg/cmd/itest)
    - [x] Move these tests to a github CI action, ideally with a matrix per environment (docker, k8s, exec, etc), or if possible: per test since they are quite long.
- [x] port `test-integ-local-exec`
    - [x] Port the shell scripts to go
- [ ] port `test-integ-local-docker`
    - [ ] Port the shell scripts to go
- [x] port `test-integ-examples`
    - [x] Port the shell scripts to go

**Comment by laurentsenta** [comment]
@galargh we had a few out-of-band discussions on this, do I remember correctly that from your experience, it'll be MUCH easier to move our test to go unit tests rather than trying things like the sharness library?

**Comment by galargh** [comment]
> @galargh we had a few out-of-band discussions on this, do I remember correctly that from your experience, it'll be MUCH easier to move our test to go unit tests rather than trying things like the sharness library?

Let's definitely stay away from sharness 👅
