### ISSUE TITLE
EPIC: Automated release process with official releases, binary distribution, and Changelogs

### ISSUE THREAD

**Issue by laurentsenta** [testground/testground#1430]
eta: 2023-01

Right now you need to build _most_ of Testground yourself before you can use the latest versions. This is not convenient for users. And more importantly, it's quite slow for CI (the setup step takes ~ 5 minutes on a github actions).

Deliverable: Automated release process with official releases, binary distribution, and Changelogs

## 1. Publish Edge releases

- [x] publish docker container for sync-service:edge
  - good starting point: `:edge` is not used there. We won't break anyone's workflow.
  - PR: https://github.com/testground/sync-service/pull/13 
- [x] publish docker containers for sidecar:edge and testground:edge
  - PR: https://github.com/testground/testground/pull/1426
- [ ] publish binary for testground:edge
  - related: https://github.com/testground/testground/issues/1300 
  - [ ] can we find a location where we can publish a binary on every merge to `master`?
  - Creating a release for every merge to master seems too noisy. Publishing the binary as a workflow outputs would work, but
    - how do we retrieve the latest artifacts of the master build?
    - do we need a cron top rerun this job at least every 90 days (the maximum retention for artifact on public projects)?

## 2. Publish "version" release

When we cut a new release we want to publish the containers & binaries

- [ ] publish docker container for sync-service:v###
- [ ] publish docker containers for sidecar:v### and testground:v###
- [ ] publish binary for testground:v###
- [ ] start implementing changelogs & automate the release creation process
- [ ] Remember to update `install.sh` scripts
  - see also https://github.com/libp2p/test-plans/pull/34#issuecomment-1233092996
 

## 3. Publish "latest" release

We want to update the tags to the latest version when we publish a new release.

- [ ] publish the `:latest` containers. ⚠️ if we published v1.0 and v2.0. If we publish a v1.1 it should NOT overwrite the `:latest` tag.

## Implement uCI

We want to dogfood the github.com/protocol/.github project with Testground.

- [ ] Integrate uCI

## Follow up Tasks

- [ ] Make the image selection in testground more explicit. Right now the code uses `:edge` images. This means you might pull `testground:0.1` and use that one. But it might end up using the `:edge` version of sidecar and sync-service, etc. 
- [ ] Publish sdk-js releases automatically
    - [ ] related CI improvements: https://github.com/testground/sdk-js/issues/27
