### ISSUE TITLE
EPIC: Documentation Improvements

### ISSUE THREAD

**Issue by laurentsenta** [testground/testground#1471]
It's not easy to get started and get deeper information on Testground,

## Related

- https://github.com/testground/testground/issues/1386#issuecomment-1254200955

## Workflow

- [ ] Make sure the documentation version default to the latest `edge` release (because that's our current default),
- [ ] Triage the docs-related issues https://github.com/testground/testground/issues?q=is%3Aissue+is%3Aopen+docs
- [ ] Triage and review the docs PR https://github.com/testground/docs/pulls

## Getting Started Issues

- [ ] https://github.com/testground/testground/issues/1424

## Going Further Issues

**Comment by laurentsenta** [comment]
@Menduist shared a tip we want to document on using docker:
https://filecoinproject.slack.com/archives/C03KQ91M0E8/p1670943190389229?thread_ts=1658418491.370399&cid=C03KQ91M0E8

> the issue I had when creating many connections is that the ARP table in linux is limited to 1024 (on my machine at least), so when doing 2k connections for instance (100 containers containers connecting to 20 containers each), it doesn't fit inside the ARP table and everything blows up.
Fix is: sudo sysctl -w net.ipv4.neigh.default.gc_thresh3=16384 or whatever floats your boat.
Posting here in case it's useful to someone (edited)
