### ISSUE TITLE
EPIC: support connecting to additional containers on the control network

### ISSUE THREAD

**Issue by laurentsenta** [testground/testground#1485]
This feature was requested and implemented in https://github.com/testground/testground/pull/1286
The statechannel team (@kerzhner and @lalexgap) is updating & completing @hannahhoward's work in https://github.com/testground/testground/pull/1481

We want to make this an official feature:

- [ ] documentation: document the parameters,
- [ ] documentation: create a guide on how to use this feature, this is a new use case,
- [ ] eks: make sure we support this feature in the k8s/eks runner (see below for the "extended" feature),
- [ ] composition: with https://github.com/testground/testground/pull/1481 we add containers to the control network on startup, it might be possible and useful, to let the user pass these as a test parameter (in their composition file probably).
  - There are multiple use cases. We'll have to identify them and decide out how far we want to go.
  - The complete solution might require having multiple control networks, which will make support in EKS and docker more complicated.
  - Simpler, intermediate solutions might let a test add new containers to the control network and won't deal with "leaks" between tests.
