### ISSUE TITLE
EPIC: Developer Experience

### ISSUE THREAD

**Issue by laurentsenta** [testground/testground#1498]
catch-all issue about improving the speed of working on and contributing to testground.

- [ ] Debugging: https://github.com/testground/testground/issues/1494
- Developping on testground
   - [ ] Testground does not re-create its satellite containers (like sidecar) when you rebuild them,
   - [ ] Testground health check crashes if you `docker rm -f` a satellite container (like sidecar) without restarting the daemon,
