### ISSUE TITLE
EPIC: EKS support, v1, A minimal installation scripts & Testground support that can run simple tests (ping & storm)

### ISSUE THREAD

**Issue by laurentsenta** [testground/testground#1499]
This is the list of issues we want to be solved or answered to merge:

- https://github.com/testground/testground/pull/1350
- https://github.com/testground/infra/pull/78

Contributes to Milestone https://github.com/testground/testground/issues/1529

## Tasks / Discussions

- [x] https://github.com/testground/testground/pull/1350#discussion_r989040850
  - @laurentsenta to review and answer first
- [x] https://github.com/testground/testground/pull/1350#discussion_r996943215
- [x] https://github.com/testground/testground/pull/1350#discussion_r986809567
- [x] Answer https://github.com/testground/infra/pull/78#issuecomment-1274467429
  - [x] Clarify the cleanup error https://github.com/testground/infra/pull/78#issuecomment-1299748843
  - [x] Clarified in https://github.com/testground/infra/pull/78#issuecomment-1307419721
- [x] ~traffic-blocked example appears broken~
   - https://github.com/testground/testground/issues/1518#issuecomment-1318367562
   - move to issue #1500 this require more work
- [x] Answer https://github.com/testground/infra/pull/78#issuecomment-1274543383, answer at least "what happens here?"
   - https://github.com/testground/infra/pull/78#issuecomment-1307419721 ("good enough")
- [ ] Fix Collect metrics https://github.com/testground/infra/pull/78#issuecomment-1280790516
  - [x] Fix implemented
  - [ ] Fix tested 
- [x] Fix the storage issue https://github.com/testground/infra/pull/78#issuecomment-1285279253

**Comment by AbominableSnowman730** [comment]
Thanks for opening the PR. 

Collect metrics was fixed [here](https://github.com/testground/testground/commit/80c5aca36114de067c33c8718cca95ef16db4c06). I'd suggest you try the next iteration of testing from the latest revision. 

We'll try to debug your cluster for the storage issue, and get back to you on the cleanup part.

**Comment by laurentsenta** [comment]
@AbominableSnowman730 I updated the ticket with links to the latest questions. Do you have an ETA for the storage issue? I'd like to run another test.

**Comment by AbominableSnowman730** [comment]
> @AbominableSnowman730 I updated the ticket with links to the latest questions. Do you have an ETA for the storage issue? I'd like to run another test.

I'd suggest running another test. We haven't been able to reproduce it with the latest version of the script,. 
It was, most likely, a side effect of the issue with the metrics collection, which was addressed a while ago.

**Comment by laurentsenta** [comment]
Will look into it; thanks for the note @AbominableSnowman730 

I updated the description to add an open check for the `traffic-blocked` example. This test verifies that the network policy "DenyAll" was applied to the container stack. It seems to indicate that we don't have the simplest network simulation feature required by Testground.

**Comment by laurentsenta** [comment]
@AbominableSnowman730 A note on storage issue: https://github.com/testground/testground/issues/1518#issuecomment-1319631728

**Comment by laurentsenta** [comment]
updated description: moved the denyall error to 1500

**Comment by laurentsenta** [comment]
@AbominableSnowman730 we'd feel like the PR will be ready to merge once the storage is fixed,
do you have an ETA on this?

(cc @galargh)

**Comment by AbominableSnowman730** [comment]
> @AbominableSnowman730 we'd feel like the PR will be ready to merge once the storage is fixed, do you have an ETA on this?
> 
> (cc @galargh)

Unfortunately, no precise ETA yet. We'll continue working on it first thing Monday.  



> * A quick note on storage, are we mounting the daemon's database storage correctly?
> 
>     * Is it possible that the daemon crashes, k8s restarts it but the storage is not there anymore?
> 
>     * Whatever fix you're coming up with, could you try to kill the daemon and check that the dashboard is not reset?

* It's mounted properly on EBS. You can see the PVC by issuing `kubectl describe pvc/testground-daemon-datadir-pvc`.
* It's persisted through daemon crashes/restarts. We've tested that scenario (i.e. it's not persisted in ephemeral containers themselves).
* We'll test that as well once we figure out what's going on. 

Let me provide a bit more information. 
All PVs that were allocated for persistence are not being destroyed/recreated (i.e. the same persistent storage is mounted to containers throughout cluster lifecycle). 
Inspecting volume contents, gives us files that were created the first time tests were ran. In our case, we've created a cluster on 2022-11-10, and we can see files present on the volume. To be more precise, LevelDB records are still there. 

You can see logs of an "expired" run by knowing the "expired" task ID (e.g. `<LB_ENDPOINT>/logs?task_id=<EXPIRED_TASK_ID>`).

**Comment by laurentsenta** [comment]
Great, thanks for sharing, It looks like the dashboard filters out tasks after a week: 
https://github.com/testground/testground/blob/ac27f8134651cfb995e54dfda81ae252b3049ff5/pkg/daemon/tasks.go#L59-L66

If the storage is correctly configured and the data is still accessible with `<LB_ENDPOINT>/logs?task_id=<EXPIRED_TASK_ID>`, I would assume this is the reason why we've seen disappearing tasks.

**Comment by galargh** [comment]
> Great, thanks for sharing, It looks like the dashboard filters out tasks after a week:
> 
> https://github.com/testground/testground/blob/ac27f8134651cfb995e54dfda81ae252b3049ff5/pkg/daemon/tasks.go#L59-L66
> 
> If the storage is correctly configured and the data is still accessible with `<LB_ENDPOINT>/logs?task_id=<EXPIRED_TASK_ID>`, I would assume this is the reason why we've seen disappearing tasks.
> 
> @galargh would you feel comfortable ticking the storage issue based on these info?

🤦 

Sure! Let's go ahead and call this endeavour complete 🥳
