### ISSUE TITLE
EKS: follow-up issues after iteration 1

### ISSUE THREAD

**Issue by laurentsenta** [testground/testground#1500]
List of issues we want to be fixed or planned before advertising Testground EKS support. This is a follow-up to https://github.com/testground/testground/issues/1499

## Tasks

Some things were not working in the previous k8s cluster and we'll have to look into this as a follow-up step,
Some things...

- [ ] Fix the deploy script redirect to isolate stdout and stderr
- [ ] Identify limitations due to [IPv6](https://github.com/testground/testground/issues/1387)
- [ ] Fix the CPU & memory measure: https://github.com/testground/infra/pull/78#issuecomment-1274410564
- [ ] Fix the dashboard links: https://github.com/testground/infra/pull/78#issuecomment-1274432225
- [ ] Fix the cleanup: https://github.com/testground/infra/pull/78#issuecomment-1274467429
- [ ] Resource constraints on the daemon: https://github.com/testground/infra/pull/78#discussion_r997923208
  - [ ] why do we use this arbitrary value?
  - [ ] verify how new test instances impact the daemon's resource usage (do we need to scale it's limits with the size of the cluster?).
- [ ] Investigate how we upgrade multus https://github.com/testground/infra/pull/78#discussion_r985850833
- [ ] Moving the CI to publish on ECR https://github.com/testground/testground/issues/1295
- [ ] Why is the testground goproxy failing "some" of the time,
- [ ] How to get logs from the testground goproxy container (we couldn't get it during the session)
- [ ] Why is testground detecting errors with graphana/prometheus/redis
- [ ] Implement a "real" automated test for the sysctl configuration (https://github.com/testground/infra/blob/4a3f62510244ea2d7e245a045d49fb0368e25507/k8s/eks/bash/functions.sh#L340)
