### ISSUE TITLE
EPIC: EKS Testing Tooling

### ISSUE THREAD

**Issue by laurentsenta** [testground/testground#1510]
Extra care is taken on Testing and Stability: we are building a testing platform, and Testground's testing must be impeccable.
EKS will require special care since it's not as easy as starting a daemon in a GitHub action.

## Phase 1: Automated smoke test in CI

- [ ] This will require a discussion on how to implement a minimal version of this.
- [ ] Run a simple smoke test that setup / use an EKS cluster
- [ ] This test should run in CI, at least nightly

## Phase 2: Run our integrations tests in EKS

- [ ] In theory, we should be able to "toggle a flag" in our integration tests and run them on our testing cluster.

## Phase 3: Add EKS to the stability dashboard

- [ ] It should be possible to push stability data into the dashboard built with https://github.com/testground/testground/issues/1401
