### ISSUE TITLE
EPIC: Well-defined Project management processes like triaging, contribution & reviewing processes, etc.

### ISSUE THREAD

**Issue by laurentsenta** [testground/testground#1511]
## Tasks

- [ ] Schedule a weekly triage session
  - [ ] retag every issue as "need triage".
- [ ] Create a project board where we can track progress on
  - triaging,
  - milestones,
  - maintenance issues (outside of any milestones).
- [ ] Refresh the https://github.com/testground/testground/blob/master/CONTRIBUTING.md doc,
- [ ] Refresh the default issues, with a clear description of what someone opening an issue needs to provide and what they might expect from the team,
- [ ] Add codeowners, stalebot via github-mgmt
- [ ] create the "root" milestone issues and update the roadmap in https://github.com/testground/testground/blob/master/ROADMAP.md

**Comment by laurentsenta** [comment]
(updated with link to https://docs.ipfs.tech/community/)
