### ISSUE TITLE
multiple runs per compositions (client-side)

### ISSUE THREAD

**Issue by laurentsenta** [testground/testground#1526]
Contributes to https://github.com/testground/testground/issues/1493

- Provide the new composition & CLI options to run "many" test plans in testground,
- Implement the feature on the client side.

## Tasks

- [x] list the templates required from https://github.com/libp2p/test-plans/tree/feat/interop-dashboard/composer and implement them
- [x] implement `pick` and `toml` and `withEnv` (https://github.com/libp2p/test-plans/blob/3fccfb27bbaba204437b93a73d8d718f4b372442/composer/demo/composition-interop.toml#L87-L97)
- [x] implement the runs field and add an option to build and run a single id (fail in other cases)
- [x] implement a way to run "all" runs at the same time and figure out a way to merge outcomes
- [x] implement a way to output the outcomes to a csv file, differentiate fail (build) and fail (run)

**Comment by laurentsenta** [comment]
Fixed with https://github.com/testground/testground/pull/1516
