### ISSUE TITLE
technical roadmap towards testground v0.5 (soft-launch)

### ISSUE THREAD

**Issue by raulk** [testground/testground#739]
> _STATUS: DRAFT_

This is an epic/tracking issue that outlines all the features and tasks we'd like to accomplish prior to the testground v0.5 release (6th May 2020, soft-launch).

## Technical

- [X] P0: Sync service rewrite
  - owner: @raulk 
  - PR: https://github.com/ipfs/testground/pull/841
- [x] P0: make the daemon a building/running engine with no knowledge of test plans.
  - owner: @raulk / @nonsense 
  - Issue: https://github.com/ipfs/testground/issues/747
  - WIP PR: https://github.com/ipfs/testground/pull/735
- [x] P0: client ships the source code of the test plan to the daemon (multipart POST with the composition + tar with source).
  - owner: @raulk / @nonsense 
  - Issue: https://github.com/ipfs/testground/issues/747
  - WIP PR: https://github.com/ipfs/testground/pull/735
- [x] P0: manifests are only used for client-side porcelain such as `testground describe`.
  - owner: @raulk / @nonsense 
  - part of issue: https://github.com/ipfs/testground/issues/747.
- [X] P0: fix client/daemon output streaming.
  - shipped in v0.4 🎉 
  - issue: https://github.com/ipfs/testground/issues/306
- [x] P0: move to the testground org.
  - owner: @raulk
  - issue: #485. 
- [x] P0: modularise the monolith.
  - owner: @raulk
  - issue: #485.
- [x] P0: move test plans out of testground.
  - owner: @raulk
  - issue: #749.
- [x] P0: take 10k scale to completion.
  - owner: @nonsense DRI, pairing with @coryschwartz 
  - issue: #599 ; #875 ; #870 ; 875 moved to v0.6
- [x] P1: client test plan management: import from git repos or from filesystem.
  - owner: @coryschwartz 
  - issue: #750
- [x] P1: using a push model with InfluxDB or Elasticsearch as our store.
  - @raulk analysing. Issue  #755
  - Workaround: delete metrics from pushgateway after plan is finished and we believe they've been scraped: #745.
- [x] P1: full healthchecks and fixes for all runners **and builders**.

## Documentation

- Launch docs.testground.ai, with the following initial content (at least):

  - What is Testground? - @raulk 
  - Prerequisites, installation and setup - @nonsense 
  - Concepts and architecture - @raulk
  - Writing test plans - @coryschwartz 
  - Building test plans - @coryschwartz 
  - Running test plans - @nonsense 
  - Collecting outputs - @nonsense 
  - Monitoring the execution environment - @nonsense + @coryschwartz 
  - Debugging - @nonsense for k8s; @raulk for local:exec; @coryschwartz local:docker.
  - Support - @Robmat05

- Launch testground.ai, pointing to this repo. - @raulk 

## Removing friction

Generally we should strive for the *principle of least surprise*, by removing quirks on all levels: codebase, UI/UX, docs.

At launch, we will have people...

- _... wanting to **try out**_ testground.

  - [x] Clear, step-by-step _getting started_ guide on the docs site.
  - [x] A sane, predictable, UI/UX.
    - [x] Intelligible, user-oriented help texts.
    - [x] Revisit naming and behaviour of switches and flags.
    - [x] Composition validation error texts are intelligible. #965
  - [x] Out-of-the-box examples that are easy to run.

- _... wanting to **adopt**_ testground in their projects.

  - [x] Superb, crisp, clear documentation on how to get started, how to operate testground, develop and run test plans, troubleshoot errors, and report issues.

- _... wanting to **investigate and contribute**_ to testground.

  - [x] Clean, navigable code base: a code base we are happy to present to the world, and stand behind.
  - [x] ~Ten (10)~ Four (4) "help-needed" issues of different complexities, that contributors can pick up and jump into.
  - [x] Clear contribution guidelines: `CONTRIBUTING.md`.

- _... wanting to **learn more**_ about testground.

  - [x] A high-level conceptual walkthrough.
  - [x] Deeper dives into each area of the system.

- _... wanting to **write test plans**_ for IPFS and libp2p.

- _... **breaking**_ testground.

  - [x] Troubleshooting guide.
  - [x] ~Revisit issue templates on this repo; dry them down.~
  - [X] ~Maybe `testground report`?~

## Communication

`<captured elsewhere>`

**Comment by raulk** [comment]
EDIT: we won't be calling this release testground v1.0 because, amongst others:
- we're still very early with regards to the actual feature set and vision of testground
- with Go and gomod, calling things v1 has ramification.s
