### ISSUE TITLE
prepare release v0.5.0 (contains checklist)

### ISSUE THREAD

**Issue by Robmat05** [testground/testground#960]
## Manual release process checklist (in order).

Release performed off branch `release/v0.5.0`.

```
NEW_VERSION=v0.5.0
```

- [ ] Tag release branch as sdk/runtime/$NEW_VERSION.
- [ ]  Push the sdk/runtime/$NEW_VERSION tag.
- [ ]  Delete all replace directives from all go.mods.
- [ ]  In sdk/iptb, go get github.com/ipfs/testground/sdk/runtime@$NEW_VERSION && go mod tidy.
- [ ]  In sdk/sync, go get github.com/ipfs/testground/sdk/runtime@$NEW_VERSION && go mod tidy.
- [ ]  In root, go get github.com/ipfs/testground/sdk/runtime@$NEW_VERSION && go mod tidy.
- [ ]  In sdk/sync/go.mod, manually bump the reference to testground to $NEW_VERSION.
- [ ]  In testground/go.mod, manually bump the reference to sdk/sync to $NEW_VERSION.
- [ ]  git commit and push all changes with message "release $NEW_VERSION."
- [ ]  Use git CLI to tag sdk/sync/$NEW_VERSION and sdk/iptb/$NEW_VERSION from release branch.
- [ ]  Push those tags to origin.
- [ ]  Use the GitHub UI to produce the testground $NEW_VERSION release by publishing the Github Release based from the release/$NEW_VERSION branch, with a nicely formatted change log and all.
- [ ]  Bump versions in master.

**Comment by raulk** [comment]
@Robmat05 this release process it outdated -- the code layout is substantially different now, and basically none of this applies. Making a release now is as simple as tagging the source, and that's it ;-)

**Comment by Robmat05** [comment]
Well, That makes things smoother. Just wanted to make sure we didn’t miss anything . Will close as discarded.
